<?php 


return [
    'Protocolo - Castelo Branco',
    'Protocolo - Palácio 12',
    'Departamento Pessoal',
    'Recursos Humanos',
    'Gabinete do Secretário de ADM',
    'Patrimônio',
    'Vigilância',
    'Controle Interno',
    'Tesouraria',
    'Contabilidade',
    'Gabinete do Prefeito',
    'DECOM',
    'IPASMI',
    'Planejamento',
    'Jurídica',
    'Ação Urbana',
    'Compras',
    'Aeroporto',
    'AMMAI',
    'Banco do Povo',
    'Contencioso Fiscal',
    'Cadastro Fiscal',
    'IPTU',
    'Funsol',
    'CRAS',
    'Vila Vida',
    'CREAS',
    'Departamento de Posturas',
    'Habitação',
    'Usina de Asfalto',
    'SMT',
    'Turismo',
];